dist: trusty
sudo: true
language: c++
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-9.0
    packages:
      - cmake
      - cmake-data
      - llvm-9.0
      - llvm-9.0-dev

script:
  - rm -rf build
  - mkdir build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR="/usr/lib/llvm-9.0/lib/cmake/llvm/" ..
  - cmake --build .
  - popd
